# Nome da pipeline que aparecerá no GitHub Actions
name: CI

# Define quando a pipeline será executada
on:

  # Executa quando houver push na branch main
  push:
    branches:
      - main

  # Executa quando houver Pull Request para a branch main
  pull_request:
    branches:
      - main

# Define os trabalhos (jobs) da pipeline
jobs:

  # Nome do job
  build-and-test:

    # Define o sistema operacional da máquina virtual usada no pipeline
    runs-on: ubuntu-latest

    # Lista de etapas que serão executadas
    steps:

      # Faz checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Instala o .NET na máquina virtual
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:

          # Define a versão do .NET utilizada
          dotnet-version: 8.0.x

      # Restaura as dependências/pacotes do projeto
      - name: Restore dependencies
        run: dotnet restore

      # Compila o projeto
      - name: Build project
        run: dotnet build --no-restore

      # Executa os testes automatizados do projeto
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
